# pipebox shell environment.
#
# /etc/profile sources this for every LOGIN shell, which covers an operator's
# ssh session. It does NOT cover the agent: nothing between crond/init and the
# Bash tool is a login shell, so pipebox-listener and pipebox-cohort-watch
# each source this file explicitly. If you add a third way to launch the
# agent, source it there too — otherwise the agent silently runs without it.
#
# GENERATED by pipebox-card from /etc/pipeos/card.conf — do not edit.
# Edit the card and re-run `pipebox-card generate`; a hand edit here is
# detected by `pipebox-card verify` and lost at the next generation.
#
# card sha256:f74d4579b6c3d0ae9b4dcf47c601c5c1b3f6758a8d0f7e56f7404f1cf4a9f8d9

# One artifact cache per box (pipeOS#90 item 1). Every checkout shares it:
# the canonical clones, PR-review scratch, probe trees. Measured on box1 the
# day this was written — /work 92% full, 36G of it repos/pipe/target, and a
# pr677-review checkout on box3 carrying its own 1.7G duplicate of artifacts
# the canonical clone already had.
#
# NOT card-driven on purpose. Card values are matched against
# [!A-Za-z0-9_.:-], so a path does not parse — and a card is data that
# arrives over HTTP from a boot server (#651), so widening that grammar to
# accept "/" to make one fleet-wide constant configurable is the wrong trade.
# This is policy, identical on every box; the card carries identity.
#
# The mountpoint test is not ceremony. /work is the ext4 workspace on a
# diskless box whose root is tmpfs. If it did not mount, exporting this
# writes gigabytes of build output into RAM, and every byte of it disappears
# under the filesystem the next time /work mounts correctly. Unset, cargo
# falls back to a per-repo target/ — the old behaviour, which is the right
# direction to fail in.
if mountpoint -q /work 2>/dev/null; then
    CARGO_TARGET_DIR=/work/cargo-target
    export CARGO_TARGET_DIR
fi
