# pipebox shell environment.
#
# /etc/profile sources this for every LOGIN shell, which covers an operator's
# ssh session. It does NOT cover the agent: nothing between crond/init and the
# Bash tool is a login shell, so pipebox-listener and pipebox-cohort-watch
# each source this file explicitly. If you add a third way to launch the
# agent, source it there too — otherwise the agent silently runs without it.
#
# GENERATED by pipebox-card from /etc/pipeos/card.conf — do not edit.
# Edit the card and re-run `pipebox-card generate`; a hand edit here is
# detected by `pipebox-card verify` and lost at the next generation.
#
# card sha256:af9d8aa25eeab85c1b9dbd506bc6f1195585799575aace329d77afd41a2c5eef

# One artifact cache per box (pipeOS#90 item 1). Every checkout shares it:
# the canonical clones, PR-review scratch, probe trees. Measured on box1 the
# day this was written — /work 92% full, 36G of it repos/pipe/target, and a
# pr677-review checkout on box3 carrying its own 1.7G duplicate of artifacts
# the canonical clone already had.
#
# NOT card-driven on purpose. Card values are matched against
# [!A-Za-z0-9_.:-], so a path does not parse — and a card is data that
# arrives over HTTP from a boot server (#651), so widening that grammar to
# accept "/" to make one fleet-wide constant configurable is the wrong trade.
# This is policy, identical on every box; the card carries identity.
#
# The mountpoint test is not ceremony. /work is the ext4 workspace on a
# diskless box whose root is tmpfs. If it did not mount, exporting this
# writes gigabytes of build output into RAM, and every byte of it disappears
# under the filesystem the next time /work mounts correctly. Unset, cargo
# falls back to a per-repo target/ — the old behaviour, which is the right
# direction to fail in.
#
# CARGO_INCREMENTAL=0 rides with it (Foreman, on #93). Incremental state is
# the largest and least useful thing in a target dir here: it is per-crate
# per-profile scratch that only pays off when the same box rebuilds the same
# working tree repeatedly with small edits. A box does short-lived
# clone-build-verdict-discard cycles across several checkouts, so the
# incremental caches are written, never read, and then counted against a
# shared /work — which is what filled it. cargo's own CI guidance is the same
# call for the same reason.
#
# Set OUTSIDE the mountpoint guard on purpose: it is a size policy, not a
# location one, and it is the correct setting whether or not /work mounted.
# Nothing about it can strand data in RAM.
CARGO_INCREMENTAL=0
export CARGO_INCREMENTAL

# CARGO_TARGET_DIR is NOT exported here any more. A single shared dir let
# cargo hand one checkout a test binary built from another (pipeOS#115,
# pipe#791) — same crate and profile, different source, green run, wrong
# code. The per-checkout keying now lives in the cargo PATH shim
# (/usr/local/bin/cargo), which resolves at invocation time — the only
# moment the current checkout is knowable. Bypassing the shim falls back to
# cargo's per-repo target/: wasteful, never wrong.
